development:
  cloud_name: dnweu15bn
  api_key: '884656219318237'
  api_secret: gf8crYIEotimlcpHco_iFlL927o
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dnweu15bn
  api_key: '884656219318237'
  api_secret: gf8crYIEotimlcpHco_iFlL927o
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dnweu15bn
  api_key: '884656219318237'
  api_secret: gf8crYIEotimlcpHco_iFlL927o
  enhance_image_tag: true
  static_image_support: false
